# Generated by Django 5.0.6 on 2024-05-15 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
