# Generated by Django 5.0.6 on 2024-05-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
