# Generated by Django 5.0.6 on 2024-05-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
