# Generated by Django 5.0.6 on 2024-05-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_rename_uploaded_at_room_created_at_remove_room_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
