# Generated by Django 5.0.6 on 2024-05-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_time',
            field=models.IntegerField(default=30),
        ),
    ]
