# Generated by Django 5.0.6 on 2024-06-12 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0002_lanfiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lanfiles',
            old_name='files',
            new_name='file',
        ),
    ]
