# Generated by Django 5.0.6 on 2024-06-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0003_rename_files_lanfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanfiles',
            name='file',
            field=models.FileField(null=True, upload_to='lanmedia'),
        ),
    ]
