# Generated by Django 5.0.6 on 2024-06-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0005_lanfiles_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanfiles',
            name='Funix_time',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='text',
            name='Tunix_time',
            field=models.IntegerField(default=30),
        ),
    ]
