# Generated by Django 5.0.6 on 2024-06-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0006_lanfiles_funix_time_text_tunix_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanfiles',
            name='Faddress',
            field=models.GenericIPAddressField(default='27.34.64.148'),
        ),
        migrations.AddField(
            model_name='text',
            name='Taddress',
            field=models.GenericIPAddressField(default='27.34.64.148'),
        ),
    ]
