# Generated by Django 5.0.6 on 2024-06-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0007_lanfiles_faddress_text_taddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanfiles',
            name='Djip',
            field=models.TextField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='Djip',
            field=models.TextField(max_length=12, null=True),
        ),
    ]
