# Generated by Django 5.0.6 on 2024-07-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0008_lanfiles_djip_text_djip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanfiles',
            name='Djip',
        ),
        migrations.RemoveField(
            model_name='text',
            name='Djip',
        ),
    ]
