# Generated by Django 5.0.6 on 2024-09-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0009_remove_lanfiles_djip_remove_text_djip'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Faddress', models.GenericIPAddressField(default='27.34.64.148')),
            ],
        ),
    ]
