# Generated by Django 5.1.1 on 2024-10-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0010_fileshistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileshistory',
            old_name='uploaded_at',
            new_name='Triggered_at',
        ),
    ]
